spring;
  datasource;
  username; root
  password; Password
url: jdbc:mysql://localhost:3306/Springbootcrud
driver-class-name: jdbc:mysql://localhost:3306/Springbootcrud
Jpa:
show-sql: true
hibernate:
ddl-auto: update
properties.hibernate.dialect: org.hybernate.dialect.MySQL5Dialeact
